AzVMMonitorV2::MainWindow
string AzVMMonitorV2.MainWindow.ClientId_appID
Defines the ClientId_appID.
Referenced by AzVMMonitorV2.MainWindow.MainWindow, AzVMMonitorV2.MainWindow.RefreshVMData, AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
string AzVMMonitorV2.MainWindow.ClientSecret_appSecret
Defines the ClientSecret_appSecret.
Referenced by AzVMMonitorV2.MainWindow.MainWindow, AzVMMonitorV2.MainWindow.RefreshVMData, AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
string AzVMMonitorV2.MainWindow.ClientTenantId
Defines the ClientTenantId.
Referenced by AzVMMonitorV2.MainWindow.MainWindow, AzVMMonitorV2.MainWindow.RefreshVMData, AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
string AzVMMonitorV2.MainWindow.AzureSubscriptionID
Defines the AzureSubscriptionID.
Referenced by AzVMMonitorV2.MainWindow.MainWindow, AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUpAsync.
string AzVMMonitorV2.MainWindow.TypeCurrency
Defines the TypeCurrency.
Referenced by AzVMMonitorV2.MainWindow.MainWindow, AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUpAsync.
double AzVMMonitorV2.MainWindow.CostVM
Defines the CostVM, CostDisks, CostNET..
Referenced by AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUpAsync.
string AzVMMonitorV2.MainWindow.vMPublcIP
Defines the vMPublcIP.
VMHelper AzVMMonitorV2.MainWindow.SelectedVM
Defines the SelectedVM.
Referenced by AzVMMonitorV2.MainWindow.ListOfVM_PreviewMouseLeftButtonDown, AzVMMonitorV2.MainWindow.ListOfVM_PreviewMouseLeftButtonUp.
IAzure AzVMMonitorV2.MainWindow.AzureCred
Defines the AzureCred.
Referenced by AzVMMonitorV2.MainWindow.RefreshVMData, AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
string AzVMMonitorV2.MainWindow.AzureTokenRESTAPI
Defines the AzureTokenRESTAPI.
Referenced by AzVMMonitorV2.MainWindow.RefreshVMData, AzVMMonitorV2.MainWindow.RefreshVMData_legacy, AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUpAsync.
List<VMHelper> AzVMMonitorV2.MainWindow.itemsVM
Defines the itemsVM.
Referenced by AzVMMonitorV2.MainWindow.Window_Loaded.
bool AzVMMonitorV2.MainWindow.isOkay
Defines the isOkay.
Referenced by AzVMMonitorV2.MainWindow.RefreshVMData, AzVMMonitorV2.MainWindow.Window_Loaded.
double AzVMMonitorV2.MainWindow.CostDisks
Referenced by AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUpAsync.
double AzVMMonitorV2.MainWindow.CostNET
Referenced by AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUpAsync.
IAzure AzVMMonitorV2.MainWindow.LogInAzure(string clientId, string clientSecret, string clientTenantId)
The LogInAzure.
clientId The clientIdstring. clientSecret The clientSecretstring. clientTenantId The clientTenantIdstring. The IAzure.
Referenced by AzVMMonitorV2.MainWindow.RefreshVMData, AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
void AzVMMonitorV2.MainWindow.Window_Loaded(object sender, RoutedEventArgs e)
The RefreshVMData.
The Window_Loaded. sender The senderobject. e The eRoutedEventArgs.
References AzVMMonitorV2.MainWindow.ConnectionToAzureTrouble, AzVMMonitorV2.MainWindow.isOkay, AzVMMonitorV2.MainWindow.itemsVM, AzVMMonitorV2.MainWindow.RefreshVMData.
void AzVMMonitorV2.MainWindow.ListOfVM_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
The ListOfVM_PreviewMouseLeftButtonDown.
sender The senderobject. e The eMouseButtonEventArgs.
References AzVMMonitorV2.MainWindow.SelectedVM, AzVMMonitorV2.VMHelper.VMState.
void AzVMMonitorV2.MainWindow.ListOfVM_PreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
The ListOfVM_PreviewMouseLeftButtonUp.
sender The senderobject. e The eMouseButtonEventArgs.
References AzVMMonitorV2.MainWindow.SelectedVM, AzVMMonitorV2.VMHelper.VMState.
void AzVMMonitorV2.MainWindow.btn_StartVM_Click(object sender, RoutedEventArgs e)
The btn_StartVM_Click.
sender The senderobject. e The eRoutedEventArgs.
References AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
void AzVMMonitorV2.MainWindow.btn_RestartVM_Click(object sender, RoutedEventArgs e)
The btn_RestartVM_Click.
sender The senderobject. e The eRoutedEventArgs.
References AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
void AzVMMonitorV2.MainWindow.btn_StopVM_Click(object sender, RoutedEventArgs e)
The btn_StopVM_Click.
sender The senderobject. e The eRoutedEventArgs.
References AzVMMonitorV2.MainWindow.RefreshVMData_legacy.
void AzVMMonitorV2.MainWindow.btn_openRDP_Click(object sender, RoutedEventArgs e)
The btn_openRDP_Click.
sender The senderobject. e The eRoutedEventArgs.
void AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
The TabItem_PreviewMouseLeftButtonUp.
sender The senderobject. e The eMouseButtonEventArgs.
void AzVMMonitorV2.MainWindow.Hyperlink_RequestNavigate_1(object sender, System.Windows.Navigation.RequestNavigateEventArgs e)
The Hyperlink_RequestNavigate_1.
sender The senderobject. e The eSystem.Windows.Navigation.RequestNavigateEventArgs.
async void AzVMMonitorV2.MainWindow.TabItem_PreviewMouseLeftButtonUpAsync(object sender, MouseButtonEventArgs e)
The TabItem_PreviewMouseLeftButtonUpAsync.
sender The senderobject. e The eMouseButtonEventArgs.
References AzVMMonitorV2.MainWindow.AzureSubscriptionID, AzVMMonitorV2.MainWindow.AzureTokenRESTAPI, AzVMMonitorV2.MainWindow.CostDisks, AzVMMonitorV2.MainWindow.CostNET, AzVMMonitorV2.MainWindow.CostVM, AzVMMonitorV2.MainWindow.TypeCurrency.
void AzVMMonitorV2.MainWindow.btn_openConfiguration_Click(object sender, RoutedEventArgs e)
The btn_openConfiguration_Click.
sender The senderobject. e The eRoutedEventArgs.
void AzVMMonitorV2.MainWindow.RefreshVMData()
The RefreshVMData.
References AzVMMonitorV2.MainWindow.AzureCred, AzVMMonitorV2.MainWindow.AzureTokenRESTAPI, AzVMMonitorV2.MainWindow.ClientId_appID, AzVMMonitorV2.MainWindow.ClientSecret_appSecret, AzVMMonitorV2.MainWindow.ClientTenantId, AzVMMonitorV2.MainWindow.isOkay, AzVMMonitorV2.MainWindow.LogInAzure.
Referenced by AzVMMonitorV2.MainWindow.Window_Loaded.
void AzVMMonitorV2.MainWindow.ConnectionToAzureTrouble()
The ConnectionToAzureTrouble.
Referenced by AzVMMonitorV2.MainWindow.Window_Loaded.
void AzVMMonitorV2.MainWindow.RefreshVMData_legacy()
The RefreshVMData_legacy.
References AzVMMonitorV2.MainWindow.AzureCred, AzVMMonitorV2.MainWindow.AzureTokenRESTAPI, AzVMMonitorV2.MainWindow.ClientId_appID, AzVMMonitorV2.MainWindow.ClientSecret_appSecret, AzVMMonitorV2.MainWindow.ClientTenantId, AzVMMonitorV2.MainWindow.LogInAzure.
Referenced by AzVMMonitorV2.MainWindow.btn_RestartVM_Click, AzVMMonitorV2.MainWindow.btn_StartVM_Click, AzVMMonitorV2.MainWindow.btn_StopVM_Click.
AzVMMonitorV2.MainWindow.MainWindow()
Initializes a new instance of the MainWindow class.
References AzVMMonitorV2.MainWindow.AzureSubscriptionID, AzVMMonitorV2.MainWindow.ClientId_appID, AzVMMonitorV2.MainWindow.ClientSecret_appSecret, AzVMMonitorV2.MainWindow.ClientTenantId, AzVMMonitorV2.MainWindow.TypeCurrency.