AzVMMonitorCostTotalData::AzBillingRESTHelper
static string AzVMMonitorCostTotalData.AzBillingRESTHelper.GetAuthorizationToken(string clientId, string clientSecret, string clientTenantId)
static async Task AzVMMonitorCostTotalData.AzBillingRESTHelper.GetTotalCost(string AccessToken, string SubscriptionID)
References AzVMMonitorCostTotalData.AzBillingRESTHelper.PostRequestAsync, AzVMMonitorCostTotalData.CostManagementQuery.requestCostManagementTotal.
static async Task AzVMMonitorCostTotalData.AzBillingRESTHelper.GetCostByVM(string AccessToken, string SubscriptionID, string VmName, string GroupName)
References AzVMMonitorCostTotalData.AzBillingRESTHelper.PostRequestAsync.
static async Task AzVMMonitorCostTotalData.AzBillingRESTHelper.GetCostByVMDisk(string AccessToken, string SubscriptionID, string VmDiskName, string GroupName)
References AzVMMonitorCostTotalData.AzBillingRESTHelper.PostRequestAsync.
static async Task AzVMMonitorCostTotalData.AzBillingRESTHelper.GetCostByVMNetwork(string AccessToken, string SubscriptionID, string VmNetworkName, string GroupName)
References AzVMMonitorCostTotalData.AzBillingRESTHelper.PostRequestAsync.
static string AzVMMonitorCostTotalData.AzBillingRESTHelper.AAAAA(string SubscriptionID, string VmName, string GroupName)
static async Task AzVMMonitorCostTotalData.AzBillingRESTHelper.getBilling1(string AccessToken, string SubscriptionID, string method)
References AzVMMonitorCostTotalData.AzBillingRESTHelper.MakeRequestAsync, AzVMMonitorCostTotalData.AzBillingRESTHelper.PostRequestAsync, AzVMMonitorCostTotalData.CostManagementQuery.requestByTagPayload.
static async Task<string> AzVMMonitorCostTotalData.AzBillingRESTHelper.GetRequestAsync(HttpRequestMessage getRequest, HttpClient client)
static async Task<string> AzVMMonitorCostTotalData.AzBillingRESTHelper.MakeRequestAsync(HttpRequestMessage getRequest, HttpClient client)
Referenced by AzVMMonitorCostTotalData.AzBillingRESTHelper.getBilling1.
static async Task<string> AzVMMonitorCostTotalData.AzBillingRESTHelper.PostRequestAsync(HttpRequestMessage postRequest, HttpClient client)
Referenced by AzVMMonitorCostTotalData.AzBillingRESTHelper.getBilling1, AzVMMonitorCostTotalData.AzBillingRESTHelper.GetCostByVM, AzVMMonitorCostTotalData.AzBillingRESTHelper.GetCostByVMDisk, AzVMMonitorCostTotalData.AzBillingRESTHelper.GetCostByVMNetwork, AzVMMonitorCostTotalData.AzBillingRESTHelper.GetTotalCost.